# Generated by Django 4.1 on 2022-11-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailganer", "0002_email_mail_to_alter_email_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="email",
            options={
                "verbose_name": "eMail адрес",
                "verbose_name_plural": "eMail адреса",
            },
        ),
        migrations.AddField(
            model_name="email",
            name="track",
            field=models.CharField(
                default="SOME STRING", max_length=3, verbose_name="Трэкер"
            ),
        ),
    ]
